export type Rule = { no: number; title: string; explanation: string };

export const rules: Rule[] = [
  { no: 1,  title: "Do not talk about /b/.",
    explanation: "There are some places you have to be part of to really appreciate. /b/ is one of them." },
  { no: 2,  title: "You do NOT talk about /b/.",
    explanation: "See rule 1, but in all caps because this time we mean it." },
  { no: 3,  title: "We are Anonymous.",
    explanation: "On the internet, everyone is anonymous. I'm anonymous, you're anonymous. No handles, no clout, no brand." },
  { no: 4,  title: "We are legion.",
    explanation: "It sounds threatening, but it really means 'many stones make a mountain'. Together we can do things nobody could alone." },
  { no: 5,  title: "Anonymous never forgives.",
    explanation: "The internet is forever. Nothing is ever really deleted. Don't be stupid unless you want to be remembered as stupid." },
  { no: 6,  title: "Anonymous can be a horrible, senseless, uncaring monster.",
    explanation: "Trolls deliberately sabotage discussions with anger-inducing comments just to watch the occupants go ballistic." },
  { no: 7,  title: "Anonymous is still able to deliver.",
    explanation: "If we all pitch in we can do amazing things together. Sometimes all it takes is one person doing something right to make a difference." },
  { no: 8,  title: "There are no real rules about posting.",
    explanation: "Site rules vary and nobody can force you to post or not post anything. Post anyway." },
  { no: 9,  title: "There are no real rules about moderation either - enjoy your ban.",
    explanation: "Caveat to rule 8: if you act stupid or break the site rules, remember that the ban hammer is always stronger than you." },
  { no: 10, title: "If you enjoy any rival sites, DON'T.",
    explanation: "Loyalty is paramount. Pick a board and commit." },
  { no: 11, title: "All your carefully picked arguments can easily be ignored.",
    explanation: "Nobody cares about your evidence. They care about being entertained." },
  { no: 12, title: "Anything you say can and will be used against you.",
    explanation: "The internet is forever. All it takes is one person with an incriminating copy." },
  { no: 13, title: "Anything you say can and will be turned into something else.",
    explanation: "Your words will be screenshot'd, remixed, memed, and weaponized. Accept it." },
  { no: 14, title: "Do not argue with trolls - it means they win.",
    explanation: "Trolls are not interested in genuine debate. The only way to defeat a troll is to ignore them, denying them attention." },
  { no: 15, title: "The harder you try, the harder you will fail.",
    explanation: "Which is more amazing: failing at making a LEGO elephant or failing at making an elephant-shaped house?" },
  { no: 16, title: "If you fail in epic proportions, it may just become a winning failure.",
    explanation: "Sometimes failures are just as impressive as success. Lean into it." },
  { no: 17, title: "Every win fails eventually.",
    explanation: "Nothing lasts forever. Enjoy your successes but don't dwell on them." },
  { no: 18, title: "Everything that can be labelled can be hated.",
    explanation: "No matter what you love, there's bound to be someone who doesn't. Labels also create judgment. Live and let live." },
  { no: 19, title: "The more you hate it, the stronger it gets.",
    explanation: "Hate is pointless. Don't waste your time on it." },
  { no: 20, title: "Nothing is to be taken seriously.",
    explanation: "If you're getting offended, you're playing the game wrong." },
  { no: 21, title: "Original content is original only for a few seconds before getting old.",
    explanation: "The shelf life of OC is measured in scrolls, not days." },
  { no: 22, title: "Copypasta is made to ruin every last bit of originality.",
    explanation: "Copy. Paste. Repeat. The natural entropy of the web." },
  { no: 23, title: "Copypasta is made to ruin every last bit of originality.",
    explanation: "Yes, this is the same as rule 22. That's the point." },
  { no: 24, title: "Every post is always a repost of a repost.",
    explanation: "People tend to save and repost things they like. In short: original content doesn't exist." },
  { no: 25, title: "Relation to the original topic decreases with every single post.",
    explanation: "As the conversation carries on, the discussion deviates widely from the original post." },
  { no: 26, title: "Any topic can be easily turned into something totally unrelated.",
    explanation: "This is the natural end state of rule 25. Embrace the drift." },
  { no: 27, title: "Always question a person's sexual preferences without any real reason.",
    explanation: "We're all anonymous and don't know each other. Better to ask than assume." },
  { no: 28, title: "Always question a person's gender - just in case it's really a man.",
    explanation: "For the sake of courtesy, ask rather than assume. Everyone is anon here." },
  { no: 29, title: "On the internet, all women are men and all kids are FBI agents.",
    explanation: "We are all anonymous, which makes gender a moot point. People who point out their genders in anonymous settings usually have ulterior motives." },
  { no: 30, title: "Girls do not exist on the internet.",
    explanation: "Saying you are a 'girl' usually denotes you're not, or you're just trying to get attention. Either way, ignore them." },
  { no: 31, title: "Tits or GTFO - the choice is yours.",
    explanation: "Any anon claiming to be a girl must provide proof. If she refuses, she's considered a liar. Classic 4chan wisdom. Apply with caution." },
  { no: 32, title: "You must have pictures to prove your statements.",
    explanation: "Pics or it didn't happen. Timestamped pictures are the gold standard of proof." },
  { no: 33, title: "Lurk more - it's never enough.",
    explanation: "When in doubt, don't post - read. Your answer is probably already somewhere. Think you know enough to post? You probably don't." },
  { no: 34, title: "There is porn of it. No exceptions.",
    explanation: "The single most famous rule. If it exists, there is porn of it. No exceptions." },
  { no: 35, title: "If no porn is found at the moment, it will be made.",
    explanation: "The corollary to rule 34. Give it 20 minutes." },
  { no: 36, title: "There will always be even more fucked up shit than what you just saw.",
    explanation: "The internet has no floor. Always deeper." },
  { no: 37, title: "You cannot divide by zero (just because the calculator says so).",
    explanation: "Nothing will never become something. Don't wrangle the site rules to your favor - it won't work." },
  { no: 38, title: "No real limits of any kind apply here - not even the sky.",
    explanation: "The internet is all the world, both good and bad, in one place. What you make of it is up to you." },
  { no: 39, title: "CAPS LOCK IS CRUISE CONTROL FOR COOL.",
    explanation: "A classic. Use sparingly." },
  { no: 40, title: "Even with cruise control you still have to steer.",
    explanation: "It's very easy to overdo memes and look like an idiot. Use caps lock with common sense." },
  { no: 41, title: "Desu isn't funny. Seriously guys.",
    explanation: "The more you post a meme, the less funny it gets. Forced memes are the death of humor." },
  { no: 42, title: "Nothing is sacred.",
    explanation: "No matter what you hold dear, prepare for others who don't get it. Respect that others may not agree. Learn to let go." },
  { no: 43, title: "The more beautiful and pure a thing is, the more satisfying it is to corrupt it.",
    explanation: "A dark truth about the internet and its inhabitants." },
  { no: 44, title: "Even one positive comment about Japanese things makes you a weeaboo.",
    explanation: "If you post even one nice thing, you're labeled a fan. Anything that can be labeled can be hated." },
  { no: 45, title: "When one sees a lion, one must get in the car.",
    explanation: "JESUS CHRIST IT'S A LION GET IN THE CAR." },
  { no: 46, title: "There is always furry porn of it.",
    explanation: "See rule 34. See also: rule 44." },
  { no: 47, title: "The pool is always closed.",
    explanation: "Slang for when jerks ruin something good. A reference to Habbo Hotel raids. The pool is closed." },
];